### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by mithro** [pepijndevos/seqpu#1]
[You can click this link](https://github.com/pepijndevos/seqpu/community/license/new?branch=master) to quickly add one.

**Comment by pepijndevos** [comment]
The question is which one... As explained by the CERN guys, you can't currently have strong copyleft on HDL as the "system libraries" exception does not apply, requiring you to open source the vendor tools and fpga silicon and what not.

It is my understanding that the Github ToS at least allows you to do some things. So I'm torn between using a legally broken copyleft license, a permissive license, or deliberately no license at all until the CERN license is ready.

**Comment by mithro** [comment]
I personally recommend just using Apache 2.0 and stop worrying about it.

**Comment by pepijndevos** [comment]
Done
